### ISSUE TITLE
yarn build:desktop

### ISSUE THREAD

**Issue by michi-zuri** [iotaledger/spark-wallet#89]
I had to rund `yarn build` before `yarn build:desktop` would work. 

Before having run `yarn build`, the output of `yarn build:desktop` was: 

```
yarn run v1.21.1
$ npm run build && tauri build
[tauri]: running build
(node:14207) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of null
    at processHTML (/Users/mimi/Sites/apps/spark-iota/github/node_modules/@tauri-apps/tauri-inliner/lib/index.js:236:55)
    at tryCallOne (/Users/mimi/Sites/apps/spark-iota/github/node_modules/promise/lib/core.js:37:12)
    at /Users/mimi/Sites/apps/spark-iota/github/node_modules/promise/lib/core.js:123:15
    at flush (/Users/mimi/Sites/apps/spark-iota/github/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
(node:14207) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14207) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 2.33s.
```

**Comment by nothingismagick** [comment]
We're aware of this behavior and a proper error message informing you that you need to build the source first before you can run `tauri build` is propegated to the console. It is in upstream and we plan to publish this weekend.

**Comment by michi-zuri** [comment]
Cool, I have some further test results:
```
error: environment variable `TAURI_CONFIG_DIR` not defined
  --> /Users/mimi/.asdf/installs/rust/1.40.0/registry/src/github.com-1ecc6299db9ec823/tauri-0.1.3/src/config.rs:75:45
   |
75 |   serde_json::from_str(include_str!(concat!(env!("TAURI_CONFIG_DIR"), "/config.json"))).unwrap()
   |                                             ^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `tauri`.
warning: build failed, waiting for other jobs to finish...
error: build failed
error: Result of `cargo build` operation was unsuccessful: exit code: 101

 app:tauri Shutting down tauri process... +1ms
✨  Done in 547.74s.
```

I had to set this environment variable to the `src-tauri` folder of my project and once the desktop app was up and running I could not Download the SeedVault:
  
![image](https://user-images.githubusercontent.com/26734536/71306674-b9349200-23e3-11ea-948b-d3fc5b6d4ef5.png)

**Comment by nothingismagick** [comment]
Regarding the downloading of the blob -> thanks for the result! Can you please file that at https://github.com/tauri-apps/tauri

And the env vars are a huge thorn in everyone's side - we are working right now on stabilizing that and it will be resolved by the time alpha lands.

**Comment by rajivshah3** [comment]
Thanks for the report @michi-zuri ! This looks like an issue with the `file-saver` package. I think it should be fixed by https://github.com/eligrey/FileSaver.js/pull/613.

I also fixed the issue with `TAURI_CONFIG_DIR` not being defined in #90
